from selenium.webdriver.common.by import By
from selenium.webdriver.support.select import Select
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP-14
    Generated by: Fredy Vargas Guarin (fredyvargu@gmail.com)
    Generated on 10/13/2021, 23:56:02
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="GlbbBp_7hxiVgiH3Ooj_-l41tKjbKUwAh7Zv5db7D48",
                              project_name="My first Project",
                              job_name="CP-14")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/proyecto/login1/Login.html"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.click()

    # 3. Type '147963' in 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.send_keys("147963")

    # 4. Click 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.click()

    # 5. Type 'root' in 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.send_keys("root")

    # 6. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input[4]")
    input1.click()

    # 7. Click 'Eliminar materia'
    eliminar_materia = driver.find_element(By.XPATH,
                                           "//a[. = 'Eliminar materia']")
    eliminar_materia.click()

    # 8. Click 'elim'
    elim = driver.find_element(By.CSS_SELECTOR,
                               "[name='elim']")
    elim.click()

    # 9. Select the 'Matematicas' option in 'elim'
    elim = driver.find_element(By.CSS_SELECTOR,
                               "[name='elim']")
    Select(elim).select_by_value("Matematicas")

    # 10. Click 'elim'
    elim = driver.find_element(By.CSS_SELECTOR,
                               "[name='elim']")
    elim.click()

    # 11. Click 'INPUT2'
    input2 = driver.find_element(By.XPATH,
                                 "//form/input")
    input2.click()

    # 12. Navigate to 'http://localhost/proyecto/php/Administrador/Administrador.php'
    driver.get("http://localhost/proyecto/php/Administrador/Administrador.php")
