from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType, TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cp - 10
    Package: TestProject.Generated.Tests.Cp10
    Test: Cp - 10
    Generated by: sebastian heredia (shr110317@gmail.com)
    Generated on 10/14/2021, 01:36:23
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="II46_CEPH6kJ62cXxGYH5LZHgzqaHGJwypw2JgYlSdk",
                              project_name="Cp - 10",
                              job_name="Cp - 10")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before,
                                 screenshot_condition=TakeScreenshotConditionType.Always)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Visualizar materias estudiante."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://localhost/proyecto/login1/Login.html"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Navigate to 'http://localhost/proyecto/login1/Login.html'
    driver.get("http://localhost/proyecto/login1/Login.html")

    # 3. Click 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.click()

    # 4. Type '55541' in 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.send_keys("55541")

    # 5. Click 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.click()

    # 6. Type 'doit' in 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.send_keys("doit")

    # 7. Click 'FORM'
    form = driver.find_element(By.XPATH,
                               "//form")
    form.click()

    # 8. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//input[4]")
    input.click()

    # 9. Click 'Materias del Programa'
    materias_del_programa = driver.find_element(By.XPATH,
                                                "//a[. = 'Materias del Programa']")
    materias_del_programa.click()
