from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: Boletín de información TC17
    Generated by: WILMER STIVEN                  MONTOYA MORENO (wsmontoya98@ucatolica.edu.co)
    Generated on 10/14/2021, 01:54:59
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="W_GF-2iJsJ5BJIBb7iZqQJrb_6FY3IOIGvt19lsAJnE",
                              project_name="My first Project",
                              job_name="Boletín de información TC17")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/proyecto/login1/Login.html"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.click()

    # 3. Type '147963' in 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.send_keys("147963")

    # 4. Click 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.click()

    # 5. Type 'root' in 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.send_keys("root")

    # 6. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//input[4]")
    input.click()

    # 7. Click 'Crear Notificacion'
    crear_notificacion = driver.find_element(By.XPATH,
                                             "//a[. = 'Crear Notificacion']")
    crear_notificacion.click()

    # 8. Click 'dat'
    dat = driver.find_element(By.CSS_SELECTOR,
                              "[name='dat']")
    dat.click()

    # 9. Type '2021-03-21' in 'dat'
    dat = driver.find_element(By.CSS_SELECTOR,
                              "[name='dat']")
    dat.send_keys("2021-03-21")

    # 10. Click 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.click()

    # 11. Type 'Wilmer' in 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.send_keys("Wilmer")

    # 12. Click 'desc'
    desc = driver.find_element(By.CSS_SELECTOR,
                               "[name='desc']")
    desc.click()

    # 13. Type 'Esta es una prueba' in 'desc'
    desc = driver.find_element(By.CSS_SELECTOR,
                               "[name='desc']")
    desc.send_keys("Esta es una prueba")

    # 14. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//input[4]")
    input.click()
