from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType, TakeScreenshotConditionType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: Cp - 10
    Package: TestProject.Generated.Tests.Cp10
    Test: Caso prueba 16
    Generated by: sebastian heredia (shr110317@gmail.com)
    Generated on 10/14/2021, 01:37:26
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="II46_CEPH6kJ62cXxGYH5LZHgzqaHGJwypw2JgYlSdk",
                              project_name="Cp - 10",
                              job_name="Caso prueba 16")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before,
                                 screenshot_condition=TakeScreenshotConditionType.Always,
                                 always_pass=True)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Publicar noticia."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://localhost/proyecto/login1/Login.html"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Navigate to 'http://localhost/proyecto/login1/Login.html'
    driver.get("http://localhost/proyecto/login1/Login.html")

    # 3. Click 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.click()

    # 4. Type '147963' in 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.send_keys("147963")

    # 5. Click 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.click()

    # 6. Type 'root' in 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.send_keys("root")

    # 7. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//input[4]")
    input.click()

    # 8. Click 'Crear Notificacion'
    crear_notificacion = driver.find_element(By.XPATH,
                                             "//a[. = 'Crear Notificacion']")
    crear_notificacion.click()

    # 9. Click 'dat'
    dat = driver.find_element(By.CSS_SELECTOR,
                              "[name='dat']")
    dat.click()

    # 10. Type '2021-09-26' in 'dat'
    dat = driver.find_element(By.CSS_SELECTOR,
                              "[name='dat']")
    dat.send_keys("2021-09-26")

    # 11. Click 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.click()

    # 12. Click 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.click()

    # 13. Type 'El futbol' in 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.send_keys("El futbol")

    # 14. Click 'semes'
    semes = driver.find_element(By.CSS_SELECTOR,
                                "[name='semes']")
    semes.click()

    # 15. Type 'Ingles' in 'semes'
    semes = driver.find_element(By.CSS_SELECTOR,
                                "[name='semes']")
    semes.send_keys("Ingles")

    # 16. Click 'desc'
    desc = driver.find_element(By.CSS_SELECTOR,
                               "[name='desc']")
    desc.click()

    # 17. Type 'El futbol el deporte mas jugado en el mundo' in 'desc'
    desc = driver.find_element(By.CSS_SELECTOR,
                               "[name='desc']")
    desc.send_keys("El futbol el deporte mas jugado en el mundo")

    # 18. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//input[4]")
    input.click()

    # 19. Navigate to 'http://localhost/proyecto/php/Administrador/Administrador.php'
    driver.get("http://localhost/proyecto/php/Administrador/Administrador.php")
