from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TC12
    Test: Boletín de información TC12
    Generated by: WILMER STIVEN                  MONTOYA MORENO (wsmontoya98@ucatolica.edu.co)
    Generated on 10/13/2021, 14:38:01
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="W_GF-2iJsJ5BJIBb7iZqQJrb_6FY3IOIGvt19lsAJnE",
                              project_name="My first Project",
                              job_name="Boletín de información TC12")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/proyecto/login1/Login.html"
    Codigo = "10076"
    Nombre = "Programación en móviles"
    Semestre = "8"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.click()

    # 3. Type '147963' in 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.send_keys("147963")

    # 4. Click 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.click()

    # 5. Type 'root' in 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.send_keys("root")

    # 6. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "//input[4]")
    input.click()

    # 7. Click 'Crear Materia'
    crear_materia = driver.find_element(By.XPATH,
                                        "//a[. = 'Crear Materia']")
    crear_materia.click()

    # 8. Click 'cod1'
    cod1 = driver.find_element(By.CSS_SELECTOR,
                               "[name='cod']")
    cod1.click()

    # 9. Type '{Codigo}' in 'cod1'
    cod1 = driver.find_element(By.CSS_SELECTOR,
                               "[name='cod']")
    cod1.send_keys(f'{Codigo}')

    # 10. Click 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.click()

    # 11. Type '{Nombre}' in 'nomb'
    nomb = driver.find_element(By.CSS_SELECTOR,
                               "[name='nomb']")
    nomb.send_keys(f'{Nombre}')

    # 12. Click 'semes'
    semes = driver.find_element(By.CSS_SELECTOR,
                                "[name='semes']")
    semes.click()

    # 13. Type '{Semestre}' in 'semes'
    semes = driver.find_element(By.CSS_SELECTOR,
                                "[name='semes']")
    semes.send_keys(f'{Semestre}')

    # 14. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//input[4]")
    input1.click()

    # 15. Click 'Cerrar Sesion'
    cerrar_sesion = driver.find_element(By.XPATH,
                                        "//a[. = 'Cerrar Sesion']")
    cerrar_sesion.click()
