from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP8 - copy
    Generated by: nicolas quintero (nic210597@gmail.com)
    Generated on 10/14/2021, 01:22:46
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="2Eq5wTBvQSEFpP0uGKHEtmg86yGL2TDPDarRn3yplA0",
                              project_name="My first Project",
                              job_name="CP8 - copy")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=1000,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/proyecto/login1/Login.html"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'cod'
    cod = driver.find_element(By.XPATH,
                              "//input[@placeholder = 'Nickname']")
    cod.click()

    # 3. Type '3006' in 'cod'
    cod = driver.find_element(By.XPATH,
                              "//input[@placeholder = 'Nickname']")
    cod.send_keys("3006")

    # 4. Click 'pass'
    _pass = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[2]")
    _pass.click()

    # 5. Type '123' in 'pass'
    _pass = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[2]")
    _pass.send_keys("123")

    # 6. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[4]")
    input.click()

    # 7. Click 'editar informacion'
    editar_informacion = driver.find_element(By.XPATH,
                                             "/html/body/div/header/div/nav/a[4]")
    editar_informacion.click()

    # 8. Click 'semes'
    semes = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[1]")
    semes.click()

    # 9. Type 'V' in 'semes'
    semes = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[1]")
    semes.send_keys("V")

    # 10. Click 'corre'
    corre = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[2]")
    corre.click()

    # 11. Type 'NIC21@GMAIL.COM' in 'corre'
    corre = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[2]")
    corre.send_keys("NIC21@GMAIL.COM")

    # 12. Click 'pass1'
    pass1 = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[3]")
    pass1.click()

    # 13. Type '123' in 'pass1'
    pass1 = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[3]")
    pass1.send_keys("123")

    # 14. Click 'INPUT'
    input = driver.find_element(By.XPATH,
                                "/html/body/div/form/input[4]")
    input.click()

    # 15. Navigate to 'http://localhost/proyecto/php/estudiante.php'
    step_settings = StepSettings(invert_result=True)
    with DriverStepSettings(driver, step_settings):
        driver.get("http://localhost/proyecto/php/estudiante.php")

    # 16. Click 'Cerrar Sesion'
    cerrar_sesion = driver.find_element(By.XPATH,
                                        "//a[. = 'Cerrar Sesion']")
    cerrar_sesion.click()
