from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP 15
    Generated by: MIGUEL ANGEL FLOREZ TRASLAVINA (maflorez14@ucatolica.edu.co)
    Generated on 10/14/2021, 01:06:16
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="XlEruqXuApR03aR7B3ihNrnu7FjCaTUK8FfUGJ-crgU",
                              project_name="My first Project",
                              job_name="CP 15")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/proyecto/login1/Login.html"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.click()

    # 3. Type '147963' in 'cod'
    cod = driver.find_element(By.CSS_SELECTOR,
                              "[name='cod']")
    cod.send_keys("147963")

    # 4. Type 'root' in 'pass'
    _pass = driver.find_element(By.CSS_SELECTOR,
                                "[name='pass']")
    _pass.send_keys("root")

    # 5. Send 'ENTER' key(s)
    ActionChains(driver).send_keys(Keys.ENTER).perform()

    # 6. Click 'Eliminar materia'
    eliminar_materia = driver.find_element(By.XPATH,
                                           "//a[. = 'Eliminar materia']")
    eliminar_materia.click()

    # 7. Click 'INPUT1'
    input1 = driver.find_element(By.XPATH,
                                 "//form/input")
    input1.click()

    # 8. Navigate to 'http://localhost/proyecto/php/Administrador/Administrador.php'
    step_settings = StepSettings(invert_result=True)
    with DriverStepSettings(driver, step_settings):
        driver.get(
            "http://localhost/proyecto/php/Administrador/Administrador.php")

    # 9. Click 'Eliminar materia1'
    eliminar_materia1 = driver.find_element(By.XPATH,
                                            "//h1[. = ' Eliminar materia ']")
    eliminar_materia1.click()
